import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import {
  uploadObjectToR2,
  getObjectFromR2,
  generateR2SignedUrl,
  deleteObjectFromR2,
  deleteObjectsFromR2,
  listObjectsFromR2,
  headObjectFromR2,
  getR2ServerConfig,
} from "./src/lib/r2Server";

const app = express();
const PORT = 3000;

// Enable CORS for all API routes so direct browser fetches / downloads work smoothly
app.use("/api", (req, res, next) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS, HEAD");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Range, Authorization, X-Requested-With");
  res.setHeader("Access-Control-Expose-Headers", "Content-Length, Content-Range, Content-Type, ETag, Content-Disposition");
  if (req.method === "OPTIONS") {
    return res.sendStatus(204);
  }
  next();
});

// Enable raw binary upload parsing for R2 uploads and JSON for API requests
app.use("/api/r2/upload", express.raw({ type: "*/*", limit: "100mb" }));
app.use(express.json({ limit: "25mb" }));

// Lazy initializer for Gemini API client
let aiClient: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiClient) {
    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("GEMINI_API_KEY environment variable is missing.");
    }
    aiClient = new GoogleGenAI({
      apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
  }
  return aiClient;
}

// System prompt instructing the AI Assistant
const SYSTEM_INSTRUCTION = `You are Sumit Tuition App's AI Assistant, an expert educational administrator and data analyst for a tuition center / coaching academy.
Your task is to analyze student, class, attendance, fee, test, homework, and syllabus structured JSON data and generate clear, professional, actionable, and encouraging reports in clean Markdown format.

RULES:
1. Format output cleanly in beautiful, well-structured Markdown with appropriate headings (##, ###), bullet points, bold highlights, and tables where helpful.
2. Provide specific, data-backed insights based on the provided JSON data.
3. Keep tone professional, empathetic, constructive, and action-oriented.
4. Highlight risks clearly (e.g. attendance < 75%, unpaid fees, declining test marks) and offer practical remediation strategies.
5. NEVER suggest or imply automatic modification of database records. All suggestions are for human review.
6. When writing parent communications, use polite, clear, and professional language with appropriate placeholders if needed.`;

// API Route: AI Report Generation
app.post("/api/ai/report", async (req, res) => {
  try {
    const { reportType, dataPayload, promptExtra } = req.body;

    if (!dataPayload) {
      return res.status(400).json({ error: "Missing dataPayload in request body" });
    }

    const ai = getGeminiClient();

    let userPrompt = `Analysis Request Type: ${reportType}\n\n`;
    userPrompt += `Provided Institution / Student Structured JSON Data:\n\`\`\`json\n${JSON.stringify(dataPayload, null, 2)}\n\`\`\`\n\n`;

    if (promptExtra) {
      userPrompt += `Additional Instructions / Focus Area:\n${promptExtra}\n\n`;
    }

    userPrompt += `Please generate the requested ${reportType} report in clean, well-formatted Markdown following the system guidance.`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: userPrompt,
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        temperature: 0.4,
      },
    });

    const markdownText = response.text || "No response generated by AI.";

    return res.json({
      success: true,
      markdown: markdownText,
      timestamp: new Date().toISOString(),
    });
  } catch (err: any) {
    console.error("Error generating AI report:", err);
    return res.status(500).json({
      error: err.message || "Failed to generate AI report. Please verify your API key and network connection.",
    });
  }
});

// API Route: Ask AI Chat Endpoint
app.post("/api/ai/chat", async (req, res) => {
  try {
    const { query, dataContext, history } = req.body;

    if (!query) {
      return res.status(400).json({ error: "Missing query in request body" });
    }

    const ai = getGeminiClient();

    let fullPrompt = `Context Data on Sumit Tuition App Institution & Students:\n\`\`\`json\n${JSON.stringify(dataContext || {}, null, 2)}\n\`\`\`\n\n`;

    if (history && Array.isArray(history) && history.length > 0) {
      fullPrompt += `Previous Conversation History:\n`;
      history.forEach((item: { role: string; text: string }) => {
        fullPrompt += `${item.role === "user" ? "Admin" : "AI Assistant"}: ${item.text}\n`;
      });
      fullPrompt += `\n`;
    }

    fullPrompt += `Admin Question: ${query}\n\n`;
    fullPrompt += `Provide a helpful, precise, and well-formatted Markdown answer based directly on the provided context data.`;

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: fullPrompt,
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        temperature: 0.3,
      },
    });

    return res.json({
      success: true,
      reply: response.text || "I could not analyze the requested query.",
    });
  } catch (err: any) {
    console.error("Error in AI Chat endpoint:", err);
    return res.status(500).json({
      error: err.message || "AI Chat failed. Please check network or API setup.",
    });
  }
});

// ========================================================
// CLOUDFLARE R2 STORAGE API ROUTES
// ========================================================

// 1. Health check & configuration status
app.get("/api/r2/health", (req, res) => {
  const config = getR2ServerConfig();
  const configured = Boolean(config.accessKeyId && config.secretAccessKey && (config.accountId || config.endpoint));
  return res.json({
    status: "ok",
    storageBackend: "Cloudflare R2",
    configured,
    bucket: config.bucket,
    hasEndpoint: Boolean(config.endpoint),
    hasPublicUrl: Boolean(config.publicUrl),
  });
});

// 2. Generate Pre-signed URL (GET or PUT)
app.post("/api/r2/signed-url", async (req, res) => {
  try {
    const { bucket, key, expiresIn, operation, contentType } = req.body;
    if (!key) {
      return res.status(400).json({ error: "Missing required 'key' parameter." });
    }

    const signedUrl = await generateR2SignedUrl({
      bucket,
      key,
      expiresIn: Number(expiresIn) || 3600,
      operation: operation === "putObject" ? "putObject" : "getObject",
      contentType,
    });

    return res.json({ success: true, signedUrl });
  } catch (err: any) {
    console.error("[Server R2] Error generating signed URL:", err);
    return res.status(500).json({
      error: err.message || "Failed to generate Cloudflare R2 signed URL.",
      stack: process.env.NODE_ENV !== "production" ? err.stack : undefined,
    });
  }
});

// 3. Upload File directly via Backend Proxy
app.post("/api/r2/upload", async (req, res) => {
  try {
    const bucket = (req.query.bucket as string) || req.body?.bucket;
    const key = (req.query.key as string) || req.body?.key;
    let contentType = (req.query.mimeType as string) || req.headers["content-type"] || "application/octet-stream";

    if (!key) {
      return res.status(400).json({ error: "Missing required 'key' query parameter or body property." });
    }

    let buffer: Buffer;
    if (Buffer.isBuffer(req.body)) {
      // Check if body is JSON with base64 payload
      const reqContentType = req.headers["content-type"] || "";
      if (reqContentType.includes("application/json")) {
        try {
          const parsed = JSON.parse(req.body.toString("utf8"));
          if (parsed.base64) {
            buffer = Buffer.from(parsed.base64, "base64");
            if (parsed.mimeType) contentType = parsed.mimeType;
          } else {
            buffer = req.body;
          }
        } catch {
          buffer = req.body;
        }
      } else {
        buffer = req.body;
      }
    } else if (req.body && typeof req.body === "object" && req.body.base64) {
      buffer = Buffer.from(req.body.base64, "base64");
      if (req.body.mimeType) contentType = req.body.mimeType;
    } else if (typeof req.body === "string") {
      buffer = Buffer.from(req.body, "utf-8");
    } else {
      return res.status(400).json({ error: "No upload body data received." });
    }

    if (!buffer || buffer.length === 0) {
      return res.status(400).json({ error: "Upload buffer is empty." });
    }

    console.log(`[Server R2] Uploading object key="${key}", size=${buffer.length} bytes, contentType="${contentType}"`);

    const result = await uploadObjectToR2({
      bucket,
      key,
      body: buffer,
      contentType,
    });

    const config = getR2ServerConfig();
    const downloadUrl = `/api/r2/download?bucket=${encodeURIComponent(result.bucket)}&key=${encodeURIComponent(key)}`;
    const publicUrl = config.publicUrl
      ? `${config.publicUrl}/${key.replace(/^\/+/, "")}`
      : downloadUrl;

    return res.json({
      success: true,
      bucket: result.bucket,
      key: result.key,
      etag: result.etag,
      url: downloadUrl,
      publicUrl: publicUrl,
      size: buffer.length,
      mimeType: contentType,
    });
  } catch (err: any) {
    console.error("[Server R2] Upload error:", {
      endpoint: "/api/r2/upload",
      error: err.message,
      stack: err.stack,
    });
    return res.status(500).json({
      error: err.message || "Failed to upload file to Cloudflare R2.",
      endpoint: "/api/r2/upload",
      stack: err.stack,
    });
  }
});

// 4. Download / Stream File from R2
app.get("/api/r2/download", async (req, res) => {
  try {
    const bucket = req.query.bucket as string | undefined;
    const key = req.query.key as string | undefined;

    if (!key) {
      return res.status(400).send("Missing required 'key' query parameter.");
    }

    const cleanKey = key.replace(/^\/+/, "");
    const range = req.headers.range;

    const obj = await getObjectFromR2({ bucket, key: cleanKey, range });

    if (!obj.body) {
      return res.status(404).send("File not found in Cloudflare R2.");
    }

    let contentType = obj.contentType || "application/octet-stream";
    if (contentType === "application/octet-stream" || !contentType) {
      if (cleanKey.toLowerCase().endsWith(".pdf")) contentType = "application/pdf";
      else if (cleanKey.toLowerCase().endsWith(".png")) contentType = "image/png";
      else if (cleanKey.toLowerCase().endsWith(".jpg") || cleanKey.toLowerCase().endsWith(".jpeg")) contentType = "image/jpeg";
      else if (cleanKey.toLowerCase().endsWith(".json")) contentType = "application/json";
    }

    res.setHeader("Content-Type", contentType);
    res.setHeader("Accept-Ranges", "bytes");
    res.setHeader("Cache-Control", "public, max-age=31536000, immutable");

    if (obj.etag) {
      res.setHeader("ETag", obj.etag);
    }

    if (obj.contentRange) {
      res.status(206);
      res.setHeader("Content-Range", obj.contentRange);
    }

    if (obj.contentLength) {
      res.setHeader("Content-Length", obj.contentLength);
    }

    if (req.query.download === "true" || req.query.filename) {
      const downloadFilename = (req.query.filename as string) || cleanKey.split("/").pop() || "download";
      res.setHeader("Content-Disposition", `attachment; filename="${encodeURIComponent(downloadFilename)}"`);
    }

    // Stream the readable response
    obj.body.pipe(res);
  } catch (err: any) {
    console.error("[Server R2] Download error:", {
      endpoint: "/api/r2/download",
      error: err.message,
      stack: err.stack,
    });
    if (err.name === "NoSuchKey" || err.name === "NotFound" || err.$metadata?.httpStatusCode === 404) {
      return res.status(404).send("File not found in Cloudflare R2.");
    }
    return res.status(500).send(`Cloudflare R2 Download Error: ${err.message || err}`);
  }
});

// 5. Delete single object
app.post("/api/r2/delete", async (req, res) => {
  try {
    const { bucket, key } = req.body;
    if (!key) {
      return res.status(400).json({ error: "Missing required 'key' parameter." });
    }

    const result = await deleteObjectFromR2({ bucket, key });
    return res.json(result);
  } catch (err: any) {
    console.error("[Server R2] Delete error:", {
      endpoint: "/api/r2/delete",
      error: err.message,
      stack: err.stack,
    });
    return res.status(500).json({
      error: err.message || "Failed to delete file from Cloudflare R2.",
      endpoint: "/api/r2/delete",
      stack: err.stack,
    });
  }
});

// 6. Delete multiple objects
app.post("/api/r2/delete-multiple", async (req, res) => {
  try {
    const { bucket, keys } = req.body;
    if (!keys || !Array.isArray(keys) || keys.length === 0) {
      return res.status(400).json({ error: "Missing or invalid 'keys' array parameter." });
    }

    const result = await deleteObjectsFromR2({ bucket, keys });
    return res.json(result);
  } catch (err: any) {
    console.error("[Server R2] Multiple delete error:", {
      endpoint: "/api/r2/delete-multiple",
      error: err.message,
      stack: err.stack,
    });
    return res.status(500).json({
      error: err.message || "Failed to delete files from Cloudflare R2.",
      endpoint: "/api/r2/delete-multiple",
      stack: err.stack,
    });
  }
});

// 7. List objects by prefix
app.post("/api/r2/list", async (req, res) => {
  try {
    const { bucket, prefix, limit, continuationToken } = req.body;
    const result = await listObjectsFromR2({
      bucket,
      prefix,
      maxKeys: Number(limit) || 1000,
      continuationToken,
    });
    return res.json(result);
  } catch (err: any) {
    console.error("[Server R2] List error:", {
      endpoint: "/api/r2/list",
      error: err.message,
      stack: err.stack,
    });
    return res.status(500).json({
      error: err.message || "Failed to list files from Cloudflare R2.",
      endpoint: "/api/r2/list",
      stack: err.stack,
    });
  }
});

// Vite Middleware & Static Production Handler
async function startServer() {
  try {
    if (process.env.NODE_ENV !== "production") {
      const hmrDisabled = process.env.DISABLE_HMR === "true";
      const vite = await createViteServer({
        server: {
          middlewareMode: true,
          hmr: hmrDisabled ? false : undefined,
        },
        appType: "spa",
      });
      app.use(vite.middlewares);
    } else {
      const distPath = path.join(process.cwd(), "dist");
      app.use(express.static(distPath));
      app.get("*", (req, res) => {
        res.sendFile(path.join(distPath, "index.html"));
      });
    }

    app.listen(PORT, "0.0.0.0", () => {
      console.log(`[Server] Production-ready Applet running on http://localhost:${PORT}`);
      console.log(`[Server] Storage Backend: Cloudflare R2 (${getR2ServerConfig().bucket})`);
    });
  } catch (error) {
    console.error("[Server] Fatal bootstrap error:", error);
    process.exit(1);
  }
}

startServer();
